ALTER TABLE "PUBLIC"."LANGUAGE" ADD COLUMN "LOCALIZED_NAME" CHARACTER VARYING(100);
ALTER TABLE "PUBLIC"."LANGUAGE" ADD COLUMN "FLAG_EMOJI" CHARACTER VARYING(16);

UPDATE "PUBLIC"."LANGUAGE"
SET
    "LOCALIZED_NAME" = CASE
        WHEN "CODE" = 'en' THEN 'English'
        WHEN "CODE" = 'ko' THEN '한국어'
        ELSE "NAME"
    END,
    "FLAG_EMOJI" = CASE
        WHEN "CODE" = 'en' THEN '🇺🇸'
        WHEN "CODE" = 'ko' THEN '🇰🇷'
        ELSE NULL
    END;

ALTER TABLE "PUBLIC"."LANGUAGE" ALTER COLUMN "LOCALIZED_NAME" SET NOT NULL;
